mongodb:
  image: mongo
  volumes:
    - /data/db:/data/db
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"

web:
  build: .
  volumes:
    - "./app:/src/app"
  ports:
    - "3031:3000"
  links:
    - mongodb